name: WCAG check & Deploy (no build, Puppeteer fix)

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Pas "SITE_DIR" aan naar de map waar je HTML staat
      # Bij GitHub Pages vaak "." (root) of "_site"
      - name: Define site directory
        run: echo "SITE_DIR=." >> $GITHUB_ENV

      - name: Install pa11y & helpers globally
        run: npm install -g pa11y wait-on serve

      - name: Install Puppeteer/Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libatk1.0-0 \
            libc6 \
            libcairo2 \
            libcups2 \
            libdbus-1-3 \
            libexpat1 \
            libfontconfig1 \
            libgbm1 \
            libgcc1 \
            libglib2.0-0 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libpango-1.0-0 \
            libpangocairo-1.0-0 \
            libstdc++6 \
            libx11-6 \
            libx11-xcb1 \
            libxcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxext6 \
            libxfixes3 \
            libxi6 \
            libxrandr2 \
            libxrender1 \
            libxss1 \
            libxtst6 \
            ca-certificates \
            fonts-liberation \
            lsb-release \
            xdg-utils \
            wget

      - name: Start local server
        run: |
          serve -s "$SITE_DIR" -l 3000 &
          npx wait-on http://localhost:3000/index.html

      - name: Run WCAG 2.1 AA check for all HTML files
        run: |
          echo "Searching for HTML files in $SITE_DIR and running WCAG checks..."
          failed=false
          for file in $(find "$SITE_DIR" -name "*.html"); do
            url="http://localhost:3000/${file#${SITE_DIR}/}"
            echo -e "\n=== Checking $url ==="
            if ! pa11y "$url" --standard=WCAG2AA --timeout=30000 --chrome-launcher-flags="--no-sandbox,--disable-setuid-sandbox"; then
              echo "Accessibility issues found on $url"
              failed=true
            fi
          done
          if [ "$failed" = true ]; then
            echo "❌ WCAG check failed for one or more pages."
            exit 1
          else
            echo "✅ All pages passed WCAG checks."
          fi

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.SITE_DIR }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
