name: Build, WCAG check & Deploy (no sitemap)

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Install pa11y & helpers
        run: npm install -g pa11y wait-on serve

      - name: Start local server
        run: |
          serve -s dist -l 3000 &
          npx wait-on http://localhost:3000

      - name: Run WCAG 2.1 AA check for all HTML files
        run: |
          echo "Searching for HTML files and running WCAG checks..."
          failed=false
          for file in $(find dist -name "*.html"); do
            # Maak URL relatief aan localhost
            url="http://localhost:3000/${file#dist/}"
            echo -e "\n=== Checking $url ==="
            if ! pa11y "$url" --standard=WCAG2AA --timeout=30000; then
              echo "Accessibility issues found on $url"
              failed=true
            fi
          done
          if [ "$failed" = true ]; then
            echo "❌ WCAG check failed for one or more pages."
            exit 1
          else
            echo "✅ All pages passed WCAG checks."
          fi

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
