name: WCAG check & Deploy (no build, Puppeteer fix)

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Pas "SITE_DIR" aan naar de map waar je HTML staat
      # Bij GitHub Pages vaak "." (root) of "_site"
      - name: Define site directory
        run: echo "SITE_DIR=." >> $GITHUB_ENV

      - name: Install pa11y & helpers globally
        run: npm install -g pa11y wait-on serve

      - name: Install pa11y locally
        run: npm install pa11y

      - name: Install Puppeteer/Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libatk1.0-0 \
            libc6 \
            libcairo2 \
            libcups2 \
            libdbus-1-3 \
            libexpat1 \
            libfontconfig1 \
            libgbm1 \
            libgcc1 \
            libglib2.0-0 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libpango-1.0-0 \
            libpangocairo-1.0-0 \
            libstdc++6 \
            libx11-6 \
            libx11-xcb1 \
            libxcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxext6 \
            libxfixes3 \
            libxi6 \
            libxrandr2 \
            libxrender1 \
            libxss1 \
            libxtst6 \
            ca-certificates \
            fonts-liberation \
            lsb-release \
            xdg-utils \
            wget

      - name: Start local server
        run: |
          serve -s "$SITE_DIR" -l 3000 &
          npx wait-on http://localhost:3000/index.html

      - name: Run WCAG 2.1 AA check for all HTML files
        run: |
          node <<'EOF'
          const pa11y = require('pa11y');
          const { execSync } = require('child_process');
          const fs = require('fs');
          const path = require('path');

          const siteDir = process.env.SITE_DIR || '.';
          const htmlFiles = execSync(`find "${siteDir}" -name "*.html"`)
            .toString()
            .trim()
            .split('\n')
            .filter(Boolean);

          (async () => {
            let failed = false;
            for (const file of htmlFiles) {
              const relativePath = file.replace(new RegExp(`^${siteDir}/?`), '');
              const url = `http://localhost:3000/${relativePath}`;
              console.log(`\n=== Checking ${url} ===`);
              try {
                await pa11y(url, {
                  standard: 'WCAG2AA',
                  timeout: 30000,
                  chromeLaunchConfig: {
                    args: ['--no-sandbox', '--disable-setuid-sandbox']
                  }
                });
              } catch (err) {
                console.error(`Accessibility issues found on ${url}`);
                failed = true;
              }
            }
            if (failed) {
              console.error("❌ WCAG check failed for one or more pages.");
              process.exit(1);
            } else {
              console.log("✅ All pages passed WCAG checks.");
            }
          })();
          EOF

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.SITE_DIR }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
