name: WCAG check and deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  wcag-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 \
            libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 \
            libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 \
            libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 \
            libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 \
            libxss1 libxtst6 ca-certificates fonts-liberation lsb-release \
            xdg-utils wget

      - name: Install pa11y locally
        run: npm install pa11y

      - name: Start local server
        run: |
          npx serve -s . -l 3000 &
          sleep 5

      - name: Run WCAG 2.1 AA check
        run: |
          node <<'EOF'
          const pa11y = require('pa11y');
          const { execSync } = require('child_process');

          const siteDir = '.'; // root van repo

          // Vind alle HTML-bestanden, maar negeer node_modules, dist, .next en verborgen mappen
          const htmlFiles = execSync(`
            find "${siteDir}" -name "*.html" \
            -not -path "*/node_modules/*" \
            -not -path "*/dist/*" \
            -not -path "*/.next/*" \
            -not -path "*/.*/*"
          `)
            .toString()
            .trim()
            .split('\n')
            .filter(Boolean);

          (async () => {
            let failed = false;
            for (const file of htmlFiles) {
              const relativePath = file.replace(new RegExp(`^${siteDir}/?`), '');
              const url = `http://localhost:3000/${relativePath}`;
              console.log(`\n=== Checking ${url} ===`);

              try {
                const results = await pa11y(url, {
                  standard: 'WCAG2AA',
                  timeout: 30000,
                  chromeLaunchConfig: {
                    args: ['--no-sandbox', '--disable-setuid-sandbox']
                  }
                });

                if (results.issues.length > 0) {
                  failed = true;
                  console.log(`\n❌ ${results.issues.length} issues found on ${url}\n`);
                  console.log('| Type       | Selector          | Message |');
                  console.log('|------------|-----------------|---------|');
                  results.issues.forEach(issue => {
                    const msg = issue.message.replace(/\|/g, '\\|');
                    console.log(`| ${issue.type.padEnd(10)} | ${issue.selector.padEnd(15)} | ${msg} |`);
                  });
                } else {
                  console.log(`✅ No issues found on ${url}`);
                }

              } catch (err) {
                console.error(`Error checking ${url}:`, err);
                failed = true;
              }
            }

            if (failed) {
              console.error("\n❌ WCAG check failed for one or more pages.");
              process.exit(1);
            } else {
              console.log("\n✅ All pages passed WCAG checks.");
            }
          })();
          EOF

      - name: Deploy to GitHub Pages
        if: ${{ success() }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
